/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.ErrorLenguaje;
import Structures.Arbol;
import Structures.Diagrama;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.StringReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.fife.ui.rsyntaxtextarea.AbstractTokenMakerFactory;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rsyntaxtextarea.SyntaxScheme;
import org.fife.ui.rsyntaxtextarea.Token;
import org.fife.ui.rsyntaxtextarea.TokenMakerFactory;
import org.fife.ui.rtextarea.RTextScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import analizadores.Analizador_Lexico;
import analizadores.Sintactico;
import analizadores.AST;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Structures.Instrucciones.Instruccion;
import Structures.Instrucciones.Main;
import Structures.Nodo;
import Structures.ReporteErrores;
import java.io.FileOutputStream;
import java.util.LinkedList;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.text.BadLocationException;
import olc_proyecto1_201900042.OLC_Proyecto1_201900042;
/**
 *
 * @author Rodrigo
 */
public class Ventana extends javax.swing.JFrame {
    RSyntaxTextArea textArea;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        jTextArea1.setEditable(false);
        RSyntax();
    }

    public LinkedList<Instruccion> resultadogo;
    public LinkedList<Instruccion> resultadopy;
    public LinkedList<Instruccion> listadiag;
    public LinkedList<ErrorLenguaje> lexerrores;
    public LinkedList<ErrorLenguaje> sintaxerrores;
    public boolean BanderaGo = false;
    public boolean BanderaPy = false;
    Nodo raiz;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelcodigo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ps-Traductor");
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(1365, 728));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Linea:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("0");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Errores:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Columna:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1033, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ps-Traductor");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/play.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/clean.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/pythonlogo.png"))); // NOI18N
        jButton3.setText("Traducir código a Python");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/golanglogo.png"))); // NOI18N
        jButton4.setText("Traducir código a Golang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        panelcodigo.setMaximumSize(new java.awt.Dimension(788, 599));
        panelcodigo.setMinimumSize(new java.awt.Dimension(788, 599));
        panelcodigo.setLayout(new java.awt.CardLayout());

        jTextArea1.setBackground(new java.awt.Color(12, 17, 22));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("Input:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Output:");

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/exportar.png"))); // NOI18N
        jButton5.setText("Exportar la Traducción");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jMenu1.setBackground(java.awt.Color.darkGray);
        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\openfile.png")); // NOI18N
        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\savefile.png")); // NOI18N
        jMenuItem2.setText("Guardar Como");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(java.awt.Color.darkGray);
        jMenu2.setText("Reporte");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\flowchart.png")); // NOI18N
        jMenuItem3.setText("Diagrama de Flujo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\error.png")); // NOI18N
        jMenuItem4.setText("Errores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\tree.png")); // NOI18N
        jMenuItem8.setText("AST");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu5.setBackground(java.awt.Color.darkGray);
        jMenu5.setText("Ver");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\userm.png")); // NOI18N
        jMenuItem6.setText("Manual de Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\OneDrive\\Documentos\\OLC1-201900042\\Proyecto 1\\OLC_Proyecto1_201900042\\src\\GUI\\Imagenes\\tecnicalm.png")); // NOI18N
        jMenuItem7.setText("Manual Técnico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CargarArchivo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (listadiag != null) {
            String codigodiag = "digraph G {\nsplines=false;\n";
            Diagrama Flowchart = new Diagrama();
            for (Instruccion ins: listadiag) {
                codigodiag += Flowchart.graficarDiagrama(ins.Diagrama());
            }
            codigodiag += "}";
            try (FileOutputStream archivo = new FileOutputStream("./Diagrama.dot")) {
                archivo.write(codigodiag.getBytes());
                archivo.close();
                Runtime.getRuntime().exec("dot -Tpdf Diagrama.dot -o Diagrama.pdf");
                Flowchart.abrirDiagrama();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero escribe correctamente tu pseudocódigo para poder mostrar el diagrama de flujo");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ReporteErrores report = new ReporteErrores(lexerrores, sintaxerrores);
        report.generarReporte();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        textArea.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(textArea.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa el pseudocodigo para poder realizar el análisis");
        }else{
            System.out.println("");
            Analizador_Lexico lexico = new Analizador_Lexico(new BufferedReader(new StringReader(textArea.getText())));
            Sintactico sintactico = new Sintactico(lexico);
            
            try {
                sintactico.parse();
                lexerrores = lexico.ErroresLexicos;
                sintaxerrores = sintactico.ErroresSintacticos;
                if(sintactico.ErroresSintacticos.size() == 0 && lexico.ErroresLexicos.size() == 0){
                    System.out.println("===========================================================================");
                    resultadogo = sintactico.TraduccionGo;
                    resultadopy = sintactico.TraduccionPy;
                    listadiag = sintactico.DiagramaF;
                    jTextArea1.setText("Analisis éxitoso, puedes comenzar a traducir");
                    OLC_Proyecto1_201900042.id_sig = 0;
                    Analizador_Lexico lexico2 = new Analizador_Lexico(new BufferedReader(new StringReader(textArea.getText())));
                    AST arbolAST = new AST(lexico2);
                    arbolAST.parse();
                    raiz = arbolAST.Raiz;
                }else{
                    String errortxt = "";
                    for (ErrorLenguaje error:lexico.ErroresLexicos) {
                        errortxt+= "Error Lexico en la linea "+error.getLinea() + ", columna " + error.getColumna()+", caracter " + error.getCaracter() + " no esperado.\n";
                    }
                    for (ErrorLenguaje error:sintactico.ErroresSintacticos) {
                        errortxt+= "Error Sintáctico en la linea "+error.getLinea() + ", columna " + error.getColumna()+", No se esperaba " + error.getCaracter() + "\n";
                    }
                    jTextArea1.setText(errortxt);
                }
            } catch (Exception ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        BanderaGo = false;
        if(!textArea.getText().equals("")){
            if(resultadopy != null){
                jTextArea1.setText("");
                int identacion = 0;
                String salidapython = "";
                for(Instruccion ins: resultadopy){
                    salidapython += ins.traductorPython(identacion);
                }
                jTextArea1.setText(salidapython);
                BanderaPy = true;
            }else{
                JOptionPane.showMessageDialog(this, "Corrige tus errores para poder exportar el código de salida.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero escribe tu pseudocódigo para poder realizar la traduccion.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser guardarArchivo = new JFileChooser();
        guardarArchivo.setDialogTitle("Guardar Como");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".olc","olc");
        guardarArchivo.setFileFilter(filtro);
        int opcion = guardarArchivo.showSaveDialog(this);
        File archivo;
        if(opcion==0){
            String nombre = guardarArchivo.getSelectedFile().getName();
            if(nombre.endsWith("olc")){
                try {
                archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath());
                if (!archivo.exists()) {
                    archivo.createNewFile();
                    FileWriter fw = new FileWriter(archivo);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(textArea.getText());
                    bw.close();
                }
                } catch (IOException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                try {
                archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath()+".olc");
                if (!archivo.exists()) {
                    archivo.createNewFile();
                    FileWriter fw = new FileWriter(archivo);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(textArea.getText());
                    bw.close();
                }
                } catch (IOException ex) {
                    Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            JOptionPane.showMessageDialog(this, "Se guardo el archivo correctamente");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BanderaPy = false;
        if(!textArea.getText().equals("")){
            if(resultadogo != null){
                int identacion = 0;
                jTextArea1.setText("");
                String salidago = "";
                for(Instruccion ins: resultadogo){
                    salidago += ins.traductorGolang(identacion);
                }
                jTextArea1.setText(salidago);
                BanderaGo = true;
            }else{
                JOptionPane.showMessageDialog(this, "Corrige tus errores para poder exportar el código de salida.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero escribe tu pseudocódigo para poder realizar la traduccion.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(!jTextArea1.getText().equals("")){
            if(BanderaGo == true || BanderaPy == true){
                if(BanderaGo == true && BanderaPy == false){
                    JFileChooser guardarArchivo = new JFileChooser();
                    guardarArchivo.setDialogTitle("Exportar Código");
                    FileNameExtensionFilter filtro = new FileNameExtensionFilter(".go","go");
                    guardarArchivo.setFileFilter(filtro);
                    int opcion = guardarArchivo.showSaveDialog(this);
                    File archivo;
                    if(opcion==0){
                        String nombre = guardarArchivo.getSelectedFile().getName();
                        if(nombre.endsWith("go")){
                            try {
                            archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath());
                            if (!archivo.exists()) {
                                archivo.createNewFile();
                                FileWriter fw = new FileWriter(archivo);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write(jTextArea1.getText());
                                bw.close();
                            }
                            } catch (IOException ex) {
                                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }else{
                            try {
                            archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath()+".go");
                            if (!archivo.exists()) {
                                archivo.createNewFile();
                                FileWriter fw = new FileWriter(archivo);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write(jTextArea1.getText());
                                bw.close();
                            }
                            } catch (IOException ex) {
                                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        JOptionPane.showMessageDialog(this, "Se exportó el código correctamente");
                    }
                }else if(BanderaGo == false && BanderaPy == true){
                    JFileChooser guardarArchivo = new JFileChooser();
                    guardarArchivo.setDialogTitle("Exportar Código");
                    FileNameExtensionFilter filtro = new FileNameExtensionFilter(".py","py");
                    guardarArchivo.setFileFilter(filtro);
                    int opcion = guardarArchivo.showSaveDialog(this);
                    File archivo;
                    if(opcion==0){
                        String nombre = guardarArchivo.getSelectedFile().getName();
                        if(nombre.endsWith("py")){
                            try {
                            archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath());
                            if (!archivo.exists()) {
                                archivo.createNewFile();
                                FileWriter fw = new FileWriter(archivo);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write(jTextArea1.getText());
                                bw.close();
                            }
                            } catch (IOException ex) {
                                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }else{
                            try {
                            archivo = new File(guardarArchivo.getSelectedFile().getAbsolutePath()+".py");
                            if (!archivo.exists()) {
                                archivo.createNewFile();
                                FileWriter fw = new FileWriter(archivo);
                                BufferedWriter bw = new BufferedWriter(fw);
                                bw.write(jTextArea1.getText());
                                bw.close();
                            }
                            } catch (IOException ex) {
                                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        JOptionPane.showMessageDialog(this, "Se exportó el código correctamente");
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Corrige tus errores para poder exportar el código de salida.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero traduce tu pseudocódigo para poder exportar el código de salida.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if(!textArea.equals("")){
            try {
                Arbol a = new Arbol();
                a.graficarAST(raiz);
            } catch (Exception ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero traduce tu pseudocódigo para poder generar el AST.");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    String contenido = "";
    File archivo;
    FileReader fr;
    BufferedReader br;
    //CARGAR EL ARCHIVO DE ENTRADA
    public void CargarArchivo(){
        try{
            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new java.io.File("."));
            fc.setDialogTitle("Cargar Archivo");
            FileNameExtensionFilter fnef = new FileNameExtensionFilter(".olc","olc");
            fc.addChoosableFileFilter(fnef);
            fc.setAcceptAllFileFilterUsed(true);
            int op = fc.showOpenDialog(this);
            if (op == JFileChooser.APPROVE_OPTION) {
                System.out.println(fc.getSelectedFile());
                archivo = fc.getSelectedFile();
            }
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                contenido += linea +"\n";
            }
            textArea.setText("");
            System.out.println(contenido);
            textArea.append(contenido);
            JOptionPane.showMessageDialog(this, "Se cargó el archivo exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "No se pudo cargar el archivo");
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        
    }
    
    public void RSyntax(){
        //CREANDO COLORES PARA EL FOREGROUND DEL LENGUAJE
        Color fondo = new Color(12, 17, 22);
        Color funciones = new Color(4, 190, 255);
        Color reservadas = new Color(221, 107, 116);
        Color identificadores = new Color(243, 133, 22);
        Color tipo_dato =new Color(132, 91, 199);
        Color literales = new Color(199, 120, 91);
        Color operadores = new Color(160, 199, 91);
        textArea = new RSyntaxTextArea();
        textArea.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent ce) {
                int pos = ce.getDot();
                try {
                    int row = textArea.getLineOfOffset(pos)+1;
                    int col = pos - textArea.getLineStartOffset(row-1)+1;
                    jLabel5.setText(String.valueOf(row));
                    jLabel7.setText(String.valueOf(col));
                } catch (BadLocationException ex) {
                    System.out.println(ex);
                }
  
            }
        });
        textArea.setFont(new Font("Monospaced",Font.PLAIN,18));
        //textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
        textArea.setHighlightCurrentLine(false);
        textArea.setBackground(fondo);
        textArea.setForeground(Color.WHITE);
        
        try{
            AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
            atmf.putMapping("text/Pseudocodigo", "Colores.Colores");
            textArea.setSyntaxEditingStyle("text/Pseudocodigo");
        }catch(Exception e){
        }
        
        RTextScrollPane sp = new RTextScrollPane(textArea);
        panelcodigo.add(sp);
        
        //AGREGANDO COLOR A LOS TOKENS
        SyntaxScheme esquema = textArea.getSyntaxScheme();
        esquema.getStyle(Token.OPERATOR).foreground = operadores;
        esquema.getStyle(Token.DATA_TYPE).foreground = tipo_dato;
        esquema.getStyle(Token.RESERVED_WORD).foreground = reservadas;
        esquema.getStyle(Token.FUNCTION).foreground=funciones;
        esquema.getStyle(Token.IDENTIFIER).foreground=identificadores;
        esquema.getStyle(Token.COMMENT_EOL).foreground=Color.GREEN;
        esquema.getStyle(Token.COMMENT_MULTILINE).foreground=Color.GREEN;
        esquema.getStyle(Token.SEPARATOR).foreground=Color.WHITE;
        esquema.getStyle(Token.LITERAL_BOOLEAN).foreground=literales;
        esquema.getStyle(Token.LITERAL_CHAR).foreground=literales;
        esquema.getStyle(Token.LITERAL_STRING_DOUBLE_QUOTE).foreground=literales;
        esquema.getStyle(Token.LITERAL_NUMBER_DECIMAL_INT).foreground=literales;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelcodigo;
    // End of variables declaration//GEN-END:variables
}
